---
- name: "Setup : Create traefik directory"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: "0550"
  loop:
    - "{{ traefik_dir }}"

- name: "Setup : Create traefik configuration"
  become: true
  ansible.builtin.copy:
    dest: "{{ traefik_dir }}/traefik.yml"
    owner: root
    group: docker
    mode: "0550"
    content: "{{ traefik_static_config | to_nice_yaml }}"
  notify:
    - Restart traefik container

- name: "Setup : Create traefik network"
  become: true
  community.docker.docker_network:
    name: "{{ traefik_network_name }}"
    ipam_config:
      - subnet: "{{ traefik_network_ipam_subnet }}"
        gateway: "{{ traefik_network_ipam_gateway }}"
        iprange: "{{ traefik_network_ipam_iprange }}"

- name: "Setup : Start traefik container"
  become: true
  community.docker.docker_container:
    name: "{{ traefik_container_name }}"
    image: "{{ traefik_image }}"
    restart_policy: unless-stopped
    published_ports: "{{ traefik_ports }}"
    volumes: "{{ traefik_volumes + traefik_add_volumes }}"
    labels: "{{ traefik_labels }}"
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    networks:
      - name: "{{ traefik_network_name }}"
    networks_cli_compatible: true
